// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqFxRBA_Gu4jNygOVNpkvTlkQ68j0k1is',
    appId: '1:499630784485:web:33fc96e25ace31fda1f90c',
    messagingSenderId: '499630784485',
    projectId: 'furnix-admin-d6849',
    authDomain: 'furnix-admin-d6849.firebaseapp.com',
    storageBucket: 'furnix-admin-d6849.appspot.com',
    measurementId: 'G-NSH3FK3X53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVNcVvTUBMMyM3PsY_Z14PUvc5TIDc4dY',
    appId: '1:499630784485:android:c2b25cda3d486b53a1f90c',
    messagingSenderId: '499630784485',
    projectId: 'furnix-admin-d6849',
    storageBucket: 'furnix-admin-d6849.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBejjl-Aps9uWz2cBJREctMGjxnrWgU0qY',
    appId: '1:499630784485:ios:4b4e2da23d400ccea1f90c',
    messagingSenderId: '499630784485',
    projectId: 'furnix-admin-d6849',
    storageBucket: 'furnix-admin-d6849.appspot.com',
    iosBundleId: 'com.example.furnixAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBejjl-Aps9uWz2cBJREctMGjxnrWgU0qY',
    appId: '1:499630784485:ios:4b4e2da23d400ccea1f90c',
    messagingSenderId: '499630784485',
    projectId: 'furnix-admin-d6849',
    storageBucket: 'furnix-admin-d6849.appspot.com',
    iosBundleId: 'com.example.furnixAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqFxRBA_Gu4jNygOVNpkvTlkQ68j0k1is',
    appId: '1:499630784485:web:a467ce29bc9250cea1f90c',
    messagingSenderId: '499630784485',
    projectId: 'furnix-admin-d6849',
    authDomain: 'furnix-admin-d6849.firebaseapp.com',
    storageBucket: 'furnix-admin-d6849.appspot.com',
    measurementId: 'G-MNG5EM2C9Q',
  );
}
